Help:
  - '/fl'
  - 'rename'
  - 'addlore'
  - 'removelore'
Reload: '&aReloaded!'
NoPermission: '&cYou have no permission for that!'
Flashlight:
  Enable: '&aFlashlight enabled'
  Disable: '&cFlashlight disabled'
  Line: '==='
Anvil:
  PreventOtherPluginsCompatibleGlitches: true
  Limit: 20
Rename:
  NoIS: '&cNo items in your hand'
  Rename: '&aItem name updated'
  Relore: '&aItem lore updated'
  ItemBlocked: '&cBAD! Dont do that please'
BlockedItems:
  - APPLE
