name: FlashLight
main: me.kvq.anvil.AnvilColors
version: 1.0
commands:
  fl:
    description: Enable/Disable flashlight
  rename:
    description: Rename an item
  addlore:
    description: Add a lore to an item
  removelore:
    description: Remove a lore from an item
